Luckyblock:
  Name: "&e&lLucky&6&lBlock"
  Lore: 
  - ""
  - "&7Break the block to get something !"
  - ""
  ParticleQuantity: 200

Lang:
  Prefix: "&f[&eVarLuckyBlock&f] "
  ReceiveLuckyBlock: "&aYou have received &e%givenumber% &aluckyblocks !"
  ReceiveByGiveall: "&aYou have received &e%givenumber% &aluckyblocks !"
  NoPerm: "&cYou don't have permission to do this."
  NoPlayer: "&cThis player does not exist or is not connected."

Events:
  1:
    Material: DIAMOND
    Data: 0
    Quantity: 32
  2:
    Material: EMERALD
    Data: 0
    Quantity: 16
  3:
    Material: DIAMOND_SWORD
    Data: 0
    Quantity: 1
    Enchantment: 
      DURABILITY: 3
  4:
    Material: TNT
    Data: 0
    Quantity: 64
  5:
    Material: GOLDEN_APPLE
    Data: 0
    Quantity: 32
  

  